name: remote ssh command

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/stdco/stdco-frontend
            git pull origin main
            npm install
            npm run build-only